---
title: "Continuous Flow Intro"
output: html_document
---

## Installation (not run)

```{r, eval=FALSE}
library(devtools)
install_github('isoread', 'sebkopf', ref = "dev")
```

## Load file

```{r load}
library(isoread)
file <- isoread(system.file("extdata", "6520__F8-5_5uL_isodat2.cf", package="isoread"), type = "H_CSIA")
```

## Raw mass data

Just the first couple of lines, not the whoel chromatogram

```{r show-data, results='asis'}
library(knitr)
kable(head(file$get_mass_data()))
```

## Plot Chromatogram

```{r ggplot}
file$make_ggplot()
```

### Time window

Only plot a specific time window and 

```{r}
file$plot_masses(tlim = c(12.3, 12.6), tunits = "min")
```

```{r}
kable(file$get_info("H3factor"), format="latex")
```

```{r}
kable(
subset(file$get_peak_table(), select = c("Peak Nr.", "Status", 
    "Ref. Peak", "Component", "Rt", "Start", "End", "Ampl. 2", 
    "d 2H/1H")),
format = "latex")
```

```{r}
map <- data.frame(Rt = c(940, 1135), Component = c("C16:0 FAME", "C18:0 FAME"), stringsAsFactors=F)
kable(map, format = "latex")
```

```{r}
file$map_peaks(map)
kable(
file$get_peak_by_name(c("C16:0 FAME", "C18:0 FAME"), 
       select = c("Peak Nr.", "Component", "Rt", "Start", "End", "Ampl. 2", "d 2H/1H")),
format = "latex")
```

```{r}
d <- file$get_peak_by_name(c("C16:0 FAME", "C18:0 FAME"), select = "d 2H/1H")
print(d) # delta value
print(switch_notation(to_abundance(d), "percent")) # abundance in percent
```

```{r}
file$plot_refs()
```

